name: action

on:
  push:
    paths:
      - rowdata/doc/postGOC/*
      - .github/workflows/docx2text.yml
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install docxtext & catdoc
      run: |
        sudo apt-get update
        sudo apt-get install docx2txt
      
    - name: run convert rowdata/doc/postGOC/*.docx to txt
      run: |
        cd rowdata/doc/postGOC/
        for i in *.docx; do docx2txt < "$i" > ../../postGOC/"$i".txt; done
        
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: commit
      run: |
        git config --global user.email jh2259@mrc-cu.cam.ac.uk
        git config --global user.name xihajun
        git add .
        git commit -m "auto save docx2txt" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
